aliasdy d 'docker'
aliasdy db 'docker build'
aliasdy di 'docker images'
aliasdy dl 'docker logs -f --tail 50'
aliasdy dpl 'docker pull'
aliasdy dps 'docker ps'
aliasdy dr 'docker run'
aliasdy drm 'docker rm'
aliasdy drmi 'docker rmi'
aliasdy drs 'docker restart'
aliasdy dsp 'docker system prune'
aliasdy dw 'docker inspect'
aliasdy dx 'docker exec -it'

aliasdy c 'docker-compose'
aliasdy cb 'docker-compose build'
aliasdy cl 'docker-compose logs -f --tail 50'
aliasdy cpl 'docker-compose pull'
aliasdy crs 'docker-compose restart'
aliasdy cu 'docker-compose up'
aliasdy cx 'docker-compose exec'
