alias d 'docker'
alias db 'docker build'
alias di 'docker images'
alias dl 'docker logs -f --tail 50'
alias dpl 'docker pull'
alias dps 'docker ps'
alias dr 'docker run'
alias drm 'docker rm'
alias drmi 'docker rmi'
alias drs 'docker restart'
alias dsp 'docker system prune'
alias dw 'docker inspect'
alias dx 'docker exec -it'

alias c 'docker-compose'
alias cb 'docker-compose build'
alias cl 'docker-compose logs -f --tail 50'
alias cpl 'docker-compose pull'
alias crs 'docker-compose restart'
alias cu 'docker-compose up'
alias cx 'docker-compose exec'
