alias G "gcloud"
alias Gc "gcloud compute"
alias Gci "gcloud compute instances"
alias Gcf "gcloud compute firewall-rules"
alias Gk "gcloud container"
alias Gp "gcloud pubsub"
alias Gs "gcloud sql"
alias Gi "gcloud iam"
alias Gl "gcloud logging"

alias fGpc "__fzf_gcloud_project_change"
alias fGcis "__fzf_gcloud_instance_search"
