alias g 'git'
alias ga 'git add'
alias gap 'ga -p'
alias gai 'ga -i'
alias gb 'git branch'
alias gbl 'git blame'
alias gc 'git commit -v'
alias gca 'gc --amend'
alias gcan 'gc --amend --no-edit --reset-author'
alias gcl 'git clean -df'
alias gco 'git checkout'
alias gcp 'git cherry-pick'
alias gd 'git diff'
alias gdb 'git branch -D'
alias gdc 'gd --cached'
alias gf 'git fetch --all -p'
alias gg 'git log --graph --pretty=format:\'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset\' --abbrev-commit --date=relative'
alias ggs 'gg --stat'
alias gl 'git pull'
alias gm 'git merge --ff'
alias gmc 'git merge --continue'
alias gmt 'git mergetool'
alias gn 'git clone --recursive'
alias gnb 'git checkout -b'
alias gp 'git push'
alias gpo 'gp -u origin'
alias grb 'git rebase'
alias grbi 'grb -i'
alias grbc 'grb --continue'
alias grh 'git reset --hard'
alias grH 'git reset HEAD'
alias grm 'git remote'
alias grs 'git reset --soft'
alias gs 'git status'
alias gsh 'git show'
alias gsm 'git submodule'
alias gsn 'git snapshot' # View my dotfile git config
alias gst 'git stash'
alias gsu 'git submodule update --init --recursive --remote'
alias gt 'git tag'
alias gw 'git whatchanged'

alias fgcs '__fzf_git_commit_search'
