aliasdy g 'git'
aliasdy ga 'git add'
aliasdy gap 'ga -p'
aliasdy gai 'ga -i'
aliasdy gb 'git branch'
aliasdy gbl 'git blame'
aliasdy gc 'git commit -v'
aliasdy gca 'gc --amend'
aliasdy gcl 'git clean -df'
aliasdy gco 'git checkout'
aliasdy gcp 'git cherry-pick'
aliasdy gd 'git diff'
aliasdy gdb 'git branch -D'
aliasdy gdc 'gd --cached'
aliasdy gf 'git fetch --all -p'
aliasdy gg 'git log --graph --pretty=format:\'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset\' --abbrev-commit --date=relative'
aliasdy ggs 'gg --stat'
aliasdy gl 'git pull'
aliasdy gm 'gf; git merge --ff'
aliasdy gmc 'git merge --continue'
aliasdy gmt 'git mergetool'
aliasdy gn 'git clone --recursive'
aliasdy gnb 'git checkout -b'
aliasdy gp 'git push'
aliasdy gpo 'gp -u origin'
aliasdy grb 'git rebase'
aliasdy grbi 'grb -i'
aliasdy grbc 'grb --continue'
aliasdy grh 'git reset --hard'
aliasdy grH 'git reset HEAD'
aliasdy grm 'git remote'
aliasdy grs 'git reset --soft'
aliasdy gs 'git status'
aliasdy gsh 'git show'
aliasdy gsm 'git submodule'
aliasdy gsn 'git snapshot' # View my dotfile git config
aliasdy gst 'git stash'
aliasdy gsu 'git submodule update --init --recursive --remote'
aliasdy gt 'git tag'
aliasdy gw 'git whatchanged'
