aliasdy k 'kubectl'
aliasdy ka 'kubectl apply -f'
aliasdy kd 'kubectl delete'
aliasdy kdc 'kubectl describe'
aliasdy ke 'kubectl edit'
aliasdy kg 'kubectl get'
aliasdy kk 'kubectl apply -k'
aliasdy kl 'kubectl logs'
aliasdy klf 'kubectl logs -f --tail 50'
aliasdy kx 'kubectl exec -it'

aliasdy h 'helm'
aliasdy hu 'helm upgrade'
aliasdy hd 'helm delete'
