alias k 'kubectl'
alias ka 'kubectl apply -f'
alias kd 'kubectl delete'
alias kdc 'kubectl describe'
alias ke 'kubectl edit'
alias kg 'kubectl get'
alias kk 'kubectl apply -k'
alias kl 'kubectl logs'
alias klf 'kubectl logs -f --tail 50'
alias kx 'kubectl exec -it'

alias h 'helm'
alias hu 'helm upgrade'
alias hd 'helm delete'
